FROM node:18.17.1

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --omit=dev

# Copy the source code
COPY ./src ./src

# Expose the app port
EXPOSE 3000

# Command to run the application
CMD npm start
