apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertise
  template:
    metadata:
      labels:
        app: advertise
    spec:
      containers:
      - name: advertise
        image: $CONTAINER_REGISTRY/advertise:2
        env:
          - name: PORT
            value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: advertise
spec:
  selector:
    app: advertise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
